server:
  port: 8050

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          "[/**]":
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: fdk
          uri: lb://FDK
          predicates:
            - Path=/van/fdk/**
          filters:
            - AddRequestHeader=sampleRequestHeader, sample
            - AddResponseHeader=sampleResponseHeader, sample
            - CustomFilter
        - id: kftc
          uri: lb://KFTC
          predicates:
            - Path=/van/kftc/**
          filters:
            - AddRequestHeader=sampleRequestHeader, sample
            - AddResponseHeader=sampleResponseHeader, sample
            - CustomFilter

eureke:
  client:
    server-url:
      default-zone: http://${EUREKA}:8761/eureka/
  instance:
    prefer-ip-address: true

EUREKA: localhost
APIGATEWAY: localhost
