package prj.yong.payment.approval.van.kftc.domain.entity;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import lombok.Data;
import lombok.NoArgsConstructor;

@NoArgsConstructor
@Data
@Entity
public class KftcTxTransanction {
    @Id @GeneratedValue
    private Long txId;
//    private Long clientRxId;
//    private String transactionType;
//    private String tidVan;
//    private String signDataDecoding;
//    private String signYn;
//    private String tranDate;
//    private String saveFg;
//    private String appDtVan;
//    private String nacoCd;
//    private String nacoNm;
//    private String cardKind;
//    private String iso;
//    private String isoHeader;
//    private String msgType;
//    private String primaryBit;
//    private String secondaryBitmap;
//    private String tranKind;
//    private String membershipPoint1;
//    private String membershipPoint2;
//    private String jmSendDt;
//    private String shopFiller;
//    private String seq;
//    private String tranTime;
//    private String productCd;
//    private String wccVan;
//    private String kikwanCdLen;
//    private String kikwanCd;
//    private String trackIiLen;
//    private String trackIi;
//    private String pgInfoLen;
//    private String pgNo;
//    private String pgDomain;
//    private String pgIpAddr;
//    private String transn;
//    private String resCd;
//    private String termId;
//    private String shopId;
//    private String bonusMsg;
//    private String usedPoint;
//    private String useablePoint;
//    private String remainPoint;
//    private String resMsg1;
//    private String resMsg2;
//    private String moneyCd;
//    private String pin;
//    private String cashIcLength;
//    private String cashIcIssueCd;
//    private String cashIcTrackiii;
//    private String cashIcEncryptData;
//    private String instMLen;
//    private String instM;
//    private String appNoLen;
//    private String appNoVan;
//    private String cardMessageLen;
//    private String vissNm;
//    private String vacoCd;
//    private String cardMsg;
//    private String emvData;
//    private String cheqLen;
//    private String cheqBank;
//    private String cheqDt;
//    private String cheqNo;
//    private String cheqMn;
//    private String cheqAmt;
//    private String cheqSeq;
//    private String remainAmt;
//    private String ispVisaData;
//    private String signDataLen;
//    private String signData;
//    private String totalAmt;
//    private String wechatLen;
//    private String wechatTradeNo;
//    private String wechatOrderNo;
//    private String cardInfoLen;
//    private String cashVissCd;
//    private String cashVissNm;
//    private String cashVissBranchCd;
//    private String cashAccountNo;
//    private String cashLedgerBalanceCd;
//    private String cashLedgerBalance;
//    private String cashRemainAmt;
//    private String cashVacoCd;
//    private String cashVacoNm;
//    private String cashVacoBranchCd;
//    private String cashChargeRate;
//    private String cashShopCharge;
//    private String cashVissCharge;
//    private String cashVacoCharge;
}
